In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
json_file = "characters.json"
characters_df = pd.read_json(json_file)
characters_df.head()

,actor,alive,ancestry,dateOfBirth,eyeColour,gender,hairColour,hogwartsStaff,hogwartsStudent,house,image,name,patronus,species,wand,yearOfBirth
0,Daniel Radcliffe,True,half-blood,31-07-1980,green,male,black,False,True,Gryffindor,http://hp-api.herokuapp.com/images/harry.jpg,Harry Potter,stag,human,"{'wood': 'holly', 'core': 'phoenix feather', '...",1980
1,Emma Watson,True,muggleborn,19-09-1979,brown,female,brown,False,True,Gryffindor,http://hp-api.herokuapp.com/images/hermione.jpeg,Hermione Granger,otter,human,"{'wood': 'vine', 'core': 'dragon heartstring',...",1979
2,Rupert Grint,True,pure-blood,01-03-1980,blue,male,red,False,True,Gryffindor,http://hp-api.herokuapp.com/images/ron.jpg,Ron Weasley,Jack Russell terrier,human,"{'wood': 'willow', 'core': 'unicorn tail-hair'...",1980
3,Tom Felton,True,pure-blood,05-06-1980,grey,male,blonde,False,True,Slytherin,http://hp-api.herokuapp.com/images/draco.jpg,Draco Malfoy,,human,"{'wood': 'hawthorn', 'core': 'unicorn tail-hai...",1980
4,Dame Maggie Smith,True,,04-10-1925,,female,black,True,False,Gryffindor,http://hp-api.herokuapp.com/images/mcgonagall.jpg,Minerva McGonagall,tabby cat,human,"{'wood': '', 'core': '', 'length': ''}",1925

In [5]:
characters_df_new = characters_df[["name", "yearOfBirth", "house", "ancestry", "eyeColour", "gender", "hogwartsStaff", "hogwartsStudent", "species", "alive"]].copy().reset_index()
characters_df_new

,index,name,yearOfBirth,house,ancestry,eyeColour,gender,hogwartsStaff,hogwartsStudent,species,alive
0,0,Harry Potter,1980,Gryffindor,half-blood,green,male,False,True,human,True
1,1,Hermione Granger,1979,Gryffindor,muggleborn,brown,female,False,True,human,True
2,2,Ron Weasley,1980,Gryffindor,pure-blood,blue,male,False,True,human,True
3,3,Draco Malfoy,1980,Slytherin,pure-blood,grey,male,False,True,human,True
4,4,Minerva McGonagall,1925,Gryffindor,,,female,True,False,human,True
5,5,Cedric Diggory,1977,Hufflepuff,,grey,male,False,True,human,False
6,6,Cho Chang,,Ravenclaw,,brown,female,False,True,human,True
7,7,Severus Snape,1960,Slytherin,half-blood,black,male,True,False,human,False
8,8,Rubeus Hagrid,1928,Gryffindor,half-blood,black,male,True,False,half-giant,True
9,9,Neville Longbottom,1980,Gryffindor,pure-blood,,male,False,True,human,True
10,10,Luna Lovegood,1981,Ravenclaw,,grey,female,False,True,human,True
11,11,Ginny Weasley,1981,Gryffindor,pure-blood,brown,female,False,True,human,True
12,12,Sirius Black,1959,Gryffindor,pure-blood,grey,male,False,False,human,False
13,13,Remus Lupin,1960,Gryffindor,half-blood,green,male,True,False,werewolf,False
14,14,Arthur Weasley,1950,Gryffindor,pure-blood,blue,male,False,False,human,True
15,15,Bellatrix Lestrange,1951,Slytherin,pure-blood,brown,female,False,False,human,False
16,16,Lord Voldemort,1926,Slytherin,half-blood,red,male,False,False,human,False
17,17,Horace Slughorn,,Slytherin,pure-blood,green,male,True,False,human,True
18,18,Kingsley Shacklebolt,,,pure-blood,brown,male,False,False,human,True
19,19,Dolores Umbridge,,Slytherin,half-blood,brown,female,True,False,human,True
20,20,Lucius Malfoy,1954,Slytherin,pure-blood,grey,male,False,False,human,True
21,21,Vincent Crabbe,,Slytherin,pure-blood,black,male,False,True,human,False
22,22,Gregory Goyle,,Slytherin,pure-blood,,male,False,True,human,True
23,23,Mrs Norris,,,,yellow,female,True,False,cat,True
24,24,Argus Filch,,,squib,,male,True,False,human,True

In [7]:
characters_df_new.columns = ["id", "name", "yearOfBirth", "house", "ancestry", "eyeColour", "gender", "hogwartsStaff", "hogwartsStudent", "species", "alive"]
characters_df_new.head()

,id,name,yearOfBirth,house,ancestry,eyeColour,gender,hogwartsStaff,hogwartsStudent,species,alive
0,0,Harry Potter,1980,Gryffindor,half-blood,green,male,False,True,human,True
1,1,Hermione Granger,1979,Gryffindor,muggleborn,brown,female,False,True,human,True
2,2,Ron Weasley,1980,Gryffindor,pure-blood,blue,male,False,True,human,True
3,3,Draco Malfoy,1980,Slytherin,pure-blood,grey,male,False,True,human,True
4,4,Minerva McGonagall,1925,Gryffindor,,,female,True,False,human,True